### ISSUE TITLE
Trims display selectively in inventory but do not in game.

### ISSUE THREAD

**Issue by DagothUrTheFalse** [ApfelRauber/StackedTrims#4]
In inventory trims display oddly, legs not visible if all armor is equipped, the helmet and boots if i take off the chestplate, and removing pants will make the helms trims show back up. Nothing else seems to effect it.

![2023-07-16_11 50 48](https://github.com/ApfelRauber/StackedTrims/assets/107820573/ec82a901-d69e-4b24-ba1a-35b6d080119f)
![2023-07-16_11 50 52](https://github.com/ApfelRauber/StackedTrims/assets/107820573/3deaa9f6-84a0-48a4-89a6-c144c4006565)
![2023-07-16_11 54 16](https://github.com/ApfelRauber/StackedTrims/assets/107820573/e2d5359d-2b5a-4a6b-9f22-8ea14c7d1ece)
![2023-07-16_11 54 22](https://github.com/ApfelRauber/StackedTrims/assets/107820573/331ad60e-1548-4122-981f-6b0a1775fb56)

**Comment by DagothUrTheFalse** [comment]
Something to do with the 2 different textures used for armor is my best guess.

**Comment by ApfelRauber** [comment]
Seems to be an issue with your texture pack since I could not reproduce this bug. What texture pack are you using? And could you try to redo the screenshots/reproduce this bug with the vanilla texture pack? I'd like to know if this is because of my mod, your texture pack or something else.

**Comment by ApfelRauber** [comment]
![grafik](https://github.com/ApfelRauber/StackedTrims/assets/57302287/209ecc21-61d3-4ac5-ba8b-01a0eaef19b1)
![grafik](https://github.com/ApfelRauber/StackedTrims/assets/57302287/609ac184-7c3e-4e3a-a44a-7f2a0e2ca351)
![grafik](https://github.com/ApfelRauber/StackedTrims/assets/57302287/ad9cca0f-4ba4-4987-82c3-0f30ad22fbc4)
![grafik](https://github.com/ApfelRauber/StackedTrims/assets/57302287/ec01f9d6-4d79-421b-a3e4-8eaa0073bdf1)

**Comment by DagothUrTheFalse** [comment]
It may be due to a different mod as I do have several installed.

![2023-07-16_12 37 58](https://github.com/ApfelRauber/StackedTrims/assets/107820573/4e334fe7-800b-4b2a-b368-5d776102f89c)
![2023-07-16_12 37 42](https://github.com/ApfelRauber/StackedTrims/assets/107820573/756e878c-186b-4ce5-80db-5d717e3c0335)

**Comment by ApfelRauber** [comment]
Can you send a list of the mods? (A screenshot of your mods folder is fine)

**Comment by DagothUrTheFalse** [comment]
Sorry i know its alot of mods.

![Screenshot_20230716_164528](https://github.com/ApfelRauber/StackedTrims/assets/107820573/fccd758a-20a9-4536-a50f-214ea818bb62)

**Comment by DagothUrTheFalse** [comment]
Odd fix but the problem wholey disappears when installing the mod AllTheTrims (different trim and resource pack used but i have double checked the issue is still present without allthetrims and without the resource pack). The issue and the fix of using AllTheTrims also seem to be present when using the similar mod Stackable Trims which was inspired by Stacked trims.

![2023-07-17_11 47 18](https://github.com/ApfelRauber/StackedTrims/assets/107820573/ab4b9eef-073f-418a-9ae2-b50c51a7099b)
![2023-07-17_11 49 30](https://github.com/ApfelRauber/StackedTrims/assets/107820573/0d809b77-60e4-4b1d-820a-c46a3ec5be07)

**Comment by ApfelRauber** [comment]
Really weird, I'll see what I can do about this bug tomorrow (ish).

**Comment by ApfelRauber** [comment]
So: This is a bug with immediatelyFast where they use Overwrite (https://github.com/RaphiMC/ImmediatelyFast/blob/1.20/src/main/java/net/raphimc/immediatelyfast/injection/mixins/core/MixinArmorFeatureRenderer.java), so I can't really do anything about this.
